//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public int Id { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string Sexo { get; set; }
        public string Cedula { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Status { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string SegundoApellido { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
